name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Publish API
        run: dotnet publish MedicalImagingStudyManager.Api/MedicalImagingStudyManager.Api.csproj --configuration Release --no-build --output publish

      - name: Upload published API
        uses: actions/upload-artifact@v4
        with:
          name: medical-imaging-study-manager-api
          path: publish
